// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uyvjbsjzywwlpzqrqzed.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV5dmpic2p6eXd3bHB6cXJxemVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2OTc3NDYsImV4cCI6MjA2NjI3Mzc0Nn0.S-xHKpF3Bc6OLMXb9iSxRQiKHKDcGUxlTURaqiLWlpg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);